project:
  type: website
  output-dir: docs

website:
  title: "Nicole Bidwell"
  navbar:
    left:
      - href: index.qmd#home
        text: Home
      - href: index.qmd#about
        text: About
      - href: index.qmd#projects
        text: Featured Work
    right:
      - href: 'https://github.com/nicolebid'
        text: "![](img/github-mark-white.png)"
      - href: 'https://www.linkedin.com/in/nicolebidwell/'
        text: "![](img/linkedin-white.png)"
             
format:
  html:
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
    css: styles.css
    toc: false
